language: objective-c  #1
os: osx
osx_image: xcode8 #2
env:
 - project= 'PanakeiaBluetooth/PanakeiaBluetooth.xcodeproj' scheme= 'PanakeiaBluetooth' platform='iOS Simulator,OS=10.0,name=iPhone SE'

script: |

  # ------ Tools ------
  set -x
  git clone https://github.com/supermarin/xcpretty.git /tmp/xcpretty
  #brew update
  #brew install carthage

  # ------ Project build ------
  echo
  echo —————— Running tests for $platform ...
  echo
  xcodebuild test \
      -project "$project" \
      -scheme "$scheme" \
      -destination "platform=$platform" \
    | /tmp/xcpretty/bin/xcpretty -c
  
  buildresult=${PIPESTATUS[0]}
  echo —————— Completed tests for $platform.
  sleep 5  # Workaround for Travis log truncation
  exit $buildresult

